name 'awsome_customers'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures awsome_customers'
long_description 'Installs/Configures awsome_customers'
version '0.1.0'
